exports.FETCH_ALL_POKEMON = "FETCH_ALL_POKEMON";
exports.ALL_POKEMON = "ALL_POKEMON";
exports.NEXT_POKEMON = "NEXT_POKEMON";
exports.MY_POKEMON = "MY_POKEMON";
exports.ADD_MY_POKEMON = "ADD_MY_POKEMON";
exports.REMOVE_MY_POKEMON = "REMOVE_MY_POKEMON";
